### ISSUE TITLE
[Proposal]  Uses of Core utilites 

### ISSUE THREAD

**Issue by random2907** [asetalias/talks#79]
### Type

Talk

### Location

Campus: Noida

### About

explaining the uses and importance of core utilites

### Duration

1 hour

### Level

Beginner

### Speakers

Ranjeet[https://github.com/random2907](url)

**Comment by Vyogami** [comment]
It's hard to schedule this talk for 1st Feb, would 8th of Feb work out for you.

**Comment by Vyogami** [comment]
Also, please elaborate what are you planning for the event!

**Comment by random2907** [comment]
> It's hard to schedule this talk for 1st Feb, would 8th of Feb work out for you.

ok .
 In this talk i use show the use of all tools in gnu coreutils and also show how they can chain it together to do complex stuff very easily using piping .

Also reference some tools which help in learning these tools.

**Comment by Vyogami** [comment]
> Also, please elaborate what are you planning for the event!

Sounds good would 8th feb work out?

**Comment by jailbreakerVC** [comment]
Hey, please also create a poster to go with it! You take inspiration from the existing ones on asetalias.in

**Comment by jailbreakerVC** [comment]
Additionally, if you need help with the poster please ask on the new volunteers group!

**Comment by chanu4321** [comment]
@jailbreakerVC @Vyogami please close this issue
